services:
  db:
    container_name: coverse-db
    image: surrealdb/surrealdb:v2.0.1
    ports:
      - "8000:8000"
        # volumes:
        #   - ./mydata:/mydata
    command:
      - start
      - --log=warn
      - --user=${SURREAL_USERNAME}
      - --pass=${SURREAL_PASSWORD}
      - --no-banner
      - --strict
    networks:
      - server-net
    restart: always
      # healthcheck:
      #   test: surreal isready --conn http://surrealdb:8000 || exit 1
      #   interval: 60s
      #   timeout: 5s
      #   retries: 2
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - SURREAL_EXPERIMENTAL_GRAPHQL=true

  migrate:
    container_name: coverse-db-migrate
    image: surrealdb/surrealdb:v2.0.1
    volumes:
      - ./surrealdb.surql:/etc/surrealdb.surql
    command:
      - import 
      - --endpoint=http://coverse-db:8000
      - --user=${SURREAL_USERNAME}
      - --pass=${SURREAL_PASSWORD}
      - --ns=test
      - --db=test
      - /etc/surrealdb.surql
    networks:
      - server-net
    depends_on:
      - db

  # docs:
  #   container_name: coverse-docs 
  #   build: ./docs 
  #   networks:
  #     - server-net

  api:
    # port 8080
    container_name: coverse-api
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true
    build: ./api
    volumes:
      - ./api/:/api
    depends_on:
      - db
      - migrate
    networks:
      - server-net
    restart: always
    labels:
      logging: "promtail"
      logging_jobname: "coverse-api"
      # command: uvicorn api.main:api --host 0.0.0.0 --port 8080 --reload
    # healthcheck:
      #   test: curl --fail http://fastapi:8080/health || exit 1
      #   interval: 60s
      #   timeout: 10s
      #   retries: 3
      #   start_period: 10s

      # caddy:
      #   image: caddy
      #   container_name: coverse-caddy
      #   command: caddy reverse-proxy --from :80 --to fastapi:8080
      #   ports:
      #     - "80:80"
      #   restart: always
      #   depends_on:
      #     - fastapi
      #   networks:
      #     - server-net
  web:
    container_name: coverse-pwa
    build: ./web_app
    volumes:
      - ./web_app/:/app
    depends_on:
      - api
    env_file:
      - ./web_app/.webapp.env
    environment:
      - COVERSE_API_URL=https://coverse-api.lamagicx.eu/api
    networks:
      - server-net
    restart: always

networks:
  server-net:
    driver: bridge
    external: true
